trigger:
  - features/*
jobs:
  - job: Compile
    displayName: 'Compile and execute unit tests'
    pool:
      vmImage: 'windows-latest'
    steps:
      - task: DotNetCoreCLI@2
        displayName: 'Restore nuget'
        inputs:
          command: 'restore'
          projects: '**/*.sln'
          feedsToUse: 'config'
          nugetConfigPath: '$(Build.SourcesDirectory)/Nuget.config'

      - task: DotNetCoreCLI@2
        displayName: 'Build solution'
        inputs:
          command: 'build'
          projects: '**/*.sln'
          arguments: '--no-restore --configuration $(buildConfiguration) --no-incremental'

      - task: DotNetCoreCLI@2
        displayName: 'Publish Unit tests'
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: '**/*.Tests.csproj'
          arguments: '--no-build --configuration $(buildConfiguration) --output out/tests'
          zipAfterPublish: false
          modifyOutputPath: false

      - task: DotNetCoreCLI@2
        displayName: 'Run unit tests'
        inputs:
          command: 'test'
          projects: 'out/tests/*.Tests.dll'
          arguments: '--collect:"XPlat Code Coverage" --logger trx --results-directory out/test-results --settings $(Build.SourcesDirectory)/src/coverlet.ut.runsettings'
          publishTestResults: false
          testRunTitle: 'Unit tests'