<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>MyDisks.Tests.Data</AssemblyName>
        <RootNamespace>MyDisks.Tests.Data</RootNamespace>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Moq.EntityFrameworkCore" Version="8.0.1.7" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Tests.Domain\Tests.Domain.csproj" />
      <ProjectReference Include="..\TestConfigurations\TestConfigurations.csproj" />
    </ItemGroup>

</Project>
