<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>MyDisks.Tests.Api</RootNamespace>
        <AssemblyName>MyDisks.Tests.Api</AssemblyName>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Api\Api.csproj"/>
        <ProjectReference Include="..\TestConfigurations\TestConfigurations.csproj" />
    </ItemGroup>

</Project>
