name: Build ⚙️
on:
  workflow_call:
    inputs:
      dotnetVersion:
        description: 'value of the .NET version'
        required: true
        type: string
      vmImage:
        description: 'image of the vm'
        required: false
        default: ubuntu-latest
        type: string
      packagePath:
        default: './publish'
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.vmImage }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnetVersion }}

      - name: Restore
        run: dotnet restore ./mydisk-api.sln

      - name: Build
        run: dotnet build ./mydisk-api.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore
        
      - name: Publish
        run: dotnet publish ./mydisk-api.sln --configuration Release --no-build --output ${{ inputs.packagePath }}