name: Build ⚙️

on:
  workflow_call:
    inputs:
      dotnetVersion:
        description: 'value of the .NET version'
        required: true
        default: '7.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnetVersion }}

      - name: Restore
        run: dotnet restore ./mydisk-api.sln

      - name: Build
        run: dotnet build ./mydisk-api.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore