name: Build ⚙️
on:
  workflow_call:
    inputs:
      dotnetVersion:
        description: 'value of the .NET version'
        required: true
        type: string
      vmImage:
        description: 'image of the vm'
        required: false
        default: ubuntu-latest
        type: string
      packagePath:
        required: true
        type: string
      artifactName:
        required: true
        type: string

jobs:
  Build:
    runs-on: ${{ inputs.vmImage }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnetVersion }}

      - name: Restore
        run: dotnet restore ./mydisk-api.sln

      - name: Build
        run: dotnet build ./mydisk-api.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore
        
      - name: Publish Unit Tests
        run: dotnet publish --configuration Release --output ${{ inputs.packagePath }}/unittest **/*.Tests.csproj

      - name: Publish unit test Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.artifactName }}
          path: ${{ inputs.packagePath }}/unittest
          
      - name: Publish Web App
        run: dotnet publish --configuration Release --output ${{ inputs.packagePath }}/webapp

      - name: Publish unit test Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.artifactName }}
          path: ${{ inputs.packagePath }}/webapp