name: Publish 🚀
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
      - features/*

env:
  PROJECTS_TO_TESTS: "['./MyDisk.Services.Tests.csproj',  './MyDisk.Api.Tests.csproj']"

jobs:
  Build:
    uses: ./.github/workflows/build-and-test.yml
    with:
      dotnetVersion: '7.x'
      packagePath: './out'
      artifactName: 'packages'
      projectToTests: "['./MyDisk.Services.Tests.csproj',  './MyDisk.Api.Tests.csproj']"
#  UnitTest:
#    needs: UnitTest
#    uses: ./.github/workflows/unit-test.yml
#    with:
#      dotnetVersion: '7.x'
#      packagePath: './out'
#      artifactName: 'packages'
    
  Deploy:
    needs: Build
    uses: ./.github/workflows/deploy.yml
    with:
      appName: 'my-disks'
      packagePath: './out'
      artifactName: 'packages'
    secrets:
      AZURE_PUBLISH_PROFILE: ${{ secrets.AZURE_PUBLISH_PROFILE }}
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Azure CLI
        uses: azure/CLI@v1

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Clone Azure Repos
        run: |
          az repos clone create --name MyDisks --organization mydisks --project MyDisks --repository MyDisks --source-url ${{ github.repository }} --source-branch ${{ github.ref }}
          cd <azure_repos>