name: Publish 🚀
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
      - features/*

jobs:
  Build:
    uses: ./.github/workflows/build-and-test.yml
    with:
      dotnetVersion: '7.x'
      packagePath: './publish'
      artifactName: 'packages'
  Deploy:
    needs: Build
    uses: ./.github/workflows/deploy.yml
    with:
      appName: 'my-disks'
      packagePath: './publish'
      artifactName: 'packages'
    secrets:
      AZURE_PUBLISH_PROFILE: ${{ secrets.AZURE_PUBLISH_PROFILE }}