name: Publish 🚀
env:
  publishProfile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
      - features/*

jobs:
  Build:
    uses: ./.github/workflows/build-and-test.yml
    with:
      dotnetVersion: '7.x'
      packagePath: './publish'
  
  publish:
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - uses: actions/checkout@v3


      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: "my-disks"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "./publish"
#  Deploy:
#    needs: Build
#    uses: ./.github/workflows/deploy.yml
#    with:
#      appName: 'my-disk'
#      packagePath: './publish'
#      publishProfile: ${{ env.publishProfile }}