name: Publish 🚀
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
      - features/*

jobs:
  Build:
    uses: ./.github/workflows/build-and-test.yml
    with:
      dotnetVersion: '7.x'
      packagePath: './publish'
  Deploy:
    needs: Build
    uses: ./.github/workflows/deploy.yml
    env:
      publishProfile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
    with:
      appName: 'my-disk'
      packagePath: './publish'
      publishProfile: publishProfile


#  publish:
#    runs-on: ubuntu-latest
#    needs: Build
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: Deployment
#        uses: azure/webapps-deploy@v2
#        with:
#          app-name: "my-disks"
#          publish-profile: ${{ env.publishProfile }}
#          package: "./publish"