name: Publish 🚀
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
      - features/*

env:
  PROJECTS_TO_TESTS: "['./MyDisk.Services.Tests.csproj',  './MyDisk.Api.Tests.csproj']"

jobs:
  Build:
    uses: ./.github/workflows/build-and-test.yml
    with:
      dotnetVersion: '7.x'
      packagePath: './out'
      artifactName: 'packages'
      projectToTests: ['./MyDisk.Services.Tests.csproj',  './MyDisk.Api.Tests.csproj']
  UnitTest:
    needs: Build
    uses: ./.github/workflows/unit-test.yml
    with:
      dotnetVersion: '7.x'
      packagePath: './out'
      artifactName: 'packages'
    
  Deploy:
    needs: UnitTest
    uses: ./.github/workflows/deploy.yml
    with:
      appName: 'my-disks'
      packagePath: './out'
      artifactName: 'packages'
    secrets:
      AZURE_PUBLISH_PROFILE: ${{ secrets.AZURE_PUBLISH_PROFILE }}