name: Publish 🚀
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
      - features/*

jobs:
  Build:
    uses: ./.github/workflows/build-and-test.yml
    with:
      dotnetVersion: '7.x'
      packagePath: './publish'
  Deploy:
    needs: Build
    uses: ./.github/workflows/deploy.yml
    with:
      appName: 'my-disk'
      packagePath: './publish'