name: Publish 🚀
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
      - features/pipeline

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore
        run: dotnet restore ./mydisk-api.sln

      - name: Build
        run: dotnet build ./mydisk-api.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./mydisk-api.sln --configuration Release --no-build
